# The first folder that contains all obsidian files
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '../obsidian-html.github.io/__src/vault/' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: '../obsidian-html.github.io/__src/vault/ObsidianHtml.md'

# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_folder_path_str:  '../obsidian-html.github.io/md/minimal'

# Markdown entrypoint path
# This has to be md_folder_path_str + '/index.md' when toggles/compile_md == True
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_entrypoint_path_str: '../obsidian-html.github.io/md/minimal/index.md'

# Output path of HTML files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
html_output_folder_path_str: '../obsidian-html.github.io/minimal'

# If extended logging is enabled under toggles/extended_logging
# Extra information is written to this folder
log_output_folder_path_str: 'output/log'

# Will be inputted into the Html template as page title
# Not used anywhere else atm.
site_name: 'ObsidianHtml/Documentation (Minimal)'

# Use when deploying to https://mydomain.com/html_prefix/ instead of https://mydomain.com/
# use '/html_prefix' (prepend slash, no slash at the end)
html_url_prefix: '/minimal'

# Provide the fullpath to a template file to use instead of standard template. 
# Note that this file must contain at least "{content}" somewhere in the page.
#html_template_path_str: '/home/dorus/git/obsidian-html/obsidianhtml/src/html/template_minimal.html'

# Exclude subfolders
# These are relative to obsidian_folder_path_str
# To exclude a folder two levels deep, use level1/level2
exclude_subfolders:
  - ".obsidian"
  - "testexclude/testexclude2"
  - ".trash"
  - ".DS_Store"
  - ".git"
  - "__src"
  - "md"
  - "obs.html"

# Safety feature: make a copy of the provided vault, and operate on that, so that bugs are less likely to affect
# the vault data. Should be fine to turn off if copying the vault takes too long / disk space is too limited.
copy_vault_to_tempdir: True

navbar_links:
  - name: Home
    link: index.html
  - name: About
    link: General Information/About ObsidianHtml.html  
  - name: Quickstart
    link: Instructions/Quickstart.html
  - name: Styling
    link: Configurations/Styling/Styling.html    
  - name: Modes
    link: Configurations/Modes.html
  - name: Features
    link: Configurations/Features.html
  - name: Configurations
    link: Configurations/Configuration Options.html
  - name: News
    link: News.html    

toggles:
  # Opt-in/-out of Obsidian->Md conversion, set to False when using proper markdown as input
  compile_md: True

  # Opt-in/-out of Md->Html conversion, set to False when only wanting to get proper markdown from Obsidian
  compile_html: True

  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: False

  # Can be overwritten ad-hoc by using "obsidianhtml -i config.yml -v" (the -v option)
  verbose_printout: False

  # Write extra information to log_output_folder_path_str
  extended_logging: True

  # This option should be False for Obsidian->Md, but can be True when compile_md == False
  # Setting it to True will cause an error when two files with the same file name are found anywhere in the input folder
  allow_duplicate_filenames_in_root: True

  # Sometimes linked images that should be local (based on the path) cannot be found.
  # Toggle this to False to disable warnings if that happens.
  warn_on_skipped_image: True

  # This will skip emptying output folders, if you want to implement this yourself
  no_clean: True

  # Whether the markdown interpreter assumes relative path when no / at the beginning of a link
  relative_path_md: True
  relative_path_html: False

  # Whether external http anchor links should have a target of "_blank"
  external_blank: False
  
  features:
    styling: 
      layout: minimal # documentation, tabs, no_tabs, minimal
      max_note_width: 70rem # not supported for layout: tabs
      add_toc: False    # add "[TOC]" (Table of Contents) when missing
      toc_pane: True   # removes table of contents from the note and puts it in the right pane (not supported for layout:tabs)
      flip_panes: True # switch right and left pane around. (does nothing unless in documentation layout.)
      accent_color: '65, 76, 253'

    theme_picker:
      enabled: False

    code_highlight:
      enabled: True

    breadcrumbs:
      enabled: True

    mermaid_diagrams:
      enabled: False

    callouts:
      enabled: True

    math_latex:
      enabled: False
      
    backlinks:
      enabled: True

    graph:
      enabled: False           # Include code to build the graph view per page (default: True)

    search:
      enabled: False

    # Create an index.md with links to notes that have one of the given tags.
    # This index.md will serve as the entrypoint
    # !! Enabling this feature will overwrite obsidian_entrypoint_path_str and md_entrypoint_path_str
    # !  Will only work for process_all: True at the moment.
    create_index_from_tags:
      enabled: False

    rss:
      enabled: False

    create_index_from_dir_structure:
      enabled: False
